apiVersion: v1
kind: Secret
metadata:
  labels:
    app: {{ .Values.rabbitmq.name }}
  namespace: {{ .Release.Namespace }}
  name: {{ .Values.rabbitmq.name }}-secret
data:
  RABBITMQ_ERLANG_COOKIE: {{ .Values.rabbitmq.config.rabbitmq_erlang_cookie | b64enc }}
type: Opaque

