apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.rabbitmq.name }}
  name: {{ .Values.rabbitmq.name }}
  namespace: {{ .Release.Namespace }}
spec:
  clusterIP: None
  ports:
  {{- range $key, $value := .Values.rabbitmq.ports }}
  - name: {{ $key }}
    port: {{ $value }}
    targetPort: {{ $value }}
  {{- end }}
  selector:
    app: {{ .Values.rabbitmq.name }}

