apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.rabbitmq.name }}
  namespace: {{ .Release.Namespace }}
spec:
  serviceName: {{ .Values.rabbitmq.name }}
  replicas: {{ .Values.rabbitmq.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.rabbitmq.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.rabbitmq.name }}
    spec:
{{- if .Values.service.nodeAffinity }}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
{{- if .Values.service.nodeAffinity.key }}
{{- if eq .Values.service.nodeAffinity.value "enabled" }}
              - key: {{ .Values.service.nodeAffinity.key }}
                operator: In
                values:
                - {{ .Values.service.nodeAffinity.value }}
{{- else }}
              - key: no-node-label
                operator: In
                values:
                - DoesNotExist
{{- end }}
{{- else }}
              - key: node-role.kubernetes.io/control-plane
                operator: DoesNotExist
              - key: node-role.kubernetes.io/master
                operator: DoesNotExist 
{{- end }}
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - {{ .Values.rabbitmq.name }}
              topologyKey: kubernetes.io/hostname
{{- end }}
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app: {{ .Values.rabbitmq.name }}
      initContainers:
      - name: {{ .Values.rabbitmq_init.name }}
        image: {{ .Values.rabbitmq_init.container.image }}
        command:
        - sh
        - -c
        - "cp /tmp/config/rabbitmq.conf /etc/rabbitmq/rabbitmq.conf && cp /tmp/config/enabled_plugins /etc/rabbitmq/enabled_plugins && ls -l /etc/rabbitmq"
        resources:
          limits:
            cpu: {{ .Values.rabbitmq_init.resources.limits.cpu }}
            memory: {{ .Values.rabbitmq_init.resources.limits.memory }}
        volumeMounts:
        - name: config
          mountPath: /etc/rabbitmq
          readOnly: false
        - name: config-files
          mountPath: /tmp/config/
          readOnly: true
      containers:
      - name: {{ .Values.rabbitmq.name }}
        image: {{ .Values.rabbitmq.container.image }}
        ports:
        {{- range $key, $value := .Values.rabbitmq.ports }}
        - containerPort: {{ $value }}
          name: {{ $key }}
        {{- end }}
        env:
        - name: RABBIT_POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: RABBIT_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: RABBITMQ_NODENAME
          value: rabbit@$(RABBIT_POD_NAME).rabbitmq.$(RABBIT_POD_NAMESPACE).svc.cluster.local
        - name: RABBITMQ_USE_LONGNAME 
          value: "true"
        - name: RABBITMQ_CONFIG_FILE
          value: "/etc/rabbitmq/rabbitmq.conf"
        - name: RABBITMQ_ERLANG_COOKIE
          valueFrom:
            secretKeyRef:
              name: {{ .Values.rabbitmq.name }}-secret
              key: RABBITMQ_ERLANG_COOKIE
        - name: K8S_HOSTNAME_SUFFIX
          value: .rabbitmq.$(RABBIT_POD_NAMESPACE).svc.cluster.local
        resources:
          limits:
            cpu: {{ .Values.rabbitmq.resources.limits.cpu }}
            memory: {{ .Values.rabbitmq.resources.limits.memory }}
          requests:
            cpu: {{ .Values.rabbitmq.resources.requests.cpu }}
            memory: {{ .Values.rabbitmq.resources.requests.memory }} 
        volumeMounts:
        - name: data
          mountPath: /var/lib/rabbitmq
          readOnly: false
      serviceAccount: {{ .Values.rabbitmq.name }}
      serviceAccountName: {{ .Values.rabbitmq.name }}
      volumes:
      - name: config
        emptyDir: {}
      - name: config-files
        configMap:
          name: {{ .Values.rabbitmq.name }}-config
          defaultMode: 0755
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes:
{{- range .Values.rabbitmq.storage.accessmodes }}
        - {{ . }}
{{- end }}
      storageClassName: {{ .Values.rabbitmq.storage.storageclass }}
      resources:
        requests:
          storage: {{ .Values.rabbitmq.storage.size }}
