apiVersion: v1
kind: Pod
metadata:
  name: vectoradd
spec:
  restartPolicy: OnFailure
  containers:
  - name: vectoradd
    image: harbor.ddtechcg.com:5001/nvidia/cuda-vector-add:v0.1
    resources:
      limits:
        nvidia.com/gpu: 1

