apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.default_http_backend.name }}
  namespace: {{ .Values.service.namespace_definition.namespace }}
  labels:
    app: {{ .Values.default_http_backend.name }}
spec:
  ports:
  - port: {{ .Values.default_http_backend.ports.port }}
    targetPort: {{ .Values.default_http_backend.ports.target_port }}
    protocol: TCP
  selector:
    app: {{ .Values.default_http_backend.name }}
