apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: {{ .Values.service.components.controller }}
    app.kubernetes.io/instance: {{ .Values.controller.name }}
    app.kubernetes.io/name: {{ .Values.controller.name }}
    app.kubernetes.io/part-of: {{ .Values.controller.name }}
    app.kubernetes.io/version: {{ .Values.service.version }}
  name: {{ .Values.controller.name }}
  namespace: {{ .Values.service.namespace_definition.namespace }}
spec:
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - appProtocol: http
    name: {{ .Values.controller.ports.http_port_name }}
    port: {{ .Values.controller.ports.http_port }}
    protocol: TCP
    targetPort: {{ .Values.controller.ports.http_port }}
  - appProtocol: https
    name: {{ .Values.controller.ports.https_port_name }}
    port: {{ .Values.controller.ports.https_port }}
    protocol: TCP
    targetPort: {{ .Values.controller.ports.https_port }}
  selector:
    app.kubernetes.io/component: {{ .Values.service.components.controller }}
    app.kubernetes.io/instance: {{ .Values.controller.name }}
    app.kubernetes.io/name: {{ .Values.controller.name }}
  type: ClusterIP
