kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.redis.name }}
  namespace: {{ .Release.Namespace }}
spec:
  clusterIP: None
  ports:
    - port: {{.Values.redis.service.port }}
      targetPort: {{.Values.redis.containerport }}
      protocol: TCP
  type: {{.Values.redis.service.type }}
  selector:
    app: {{ .Values.redis.name }}

