apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fetch-cluster-info-pod
rules:
- apiGroups:
  - ""
  resources:
  - "configmaps"
  resourceNames:
  - "kubeadm-config"
  verbs:
  - get
  - list

