apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: {{ .Values.metrics_server.name }}
  name: system:{{ .Values.metrics_server.name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:{{ .Values.metrics_server.name }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.metrics_server.name }}
  namespace: {{ .Values.env.namespace }}

