apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: test-cluster
  region: us-east-2
  version: "1.36"

nodeGroups:
  - name: test-cluster-nodes
    instanceType: t3.micro
    ami: ami-0df2fc7cc198fb009          # Your custom AMI ID (Required)
    amiFamily: Ubuntu2404               # Operating system family
    minSize: 1
    desiredCapacity: 2
    maxSize: 3
    volumeSize: 40
    overrideBootstrapCommand: |
      #!/bin/bash
      source /var/lib/cloud/scripts/eksctl/bootstrap.helper.sh
      /etc/eks/bootstrap.sh ${CLUSTER_NAME} --container-runtime containerd --kubelet-extra-args "--node-labels=workload=cpu"
    ssh:
      allow: true
