apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/component: {{ .Values.service.components.admission_webhook }}
    app.kubernetes.io/instance: {{ .Values.controller.name }}
    app.kubernetes.io/name: {{ .Values.controller.name }}
    app.kubernetes.io/part-of: {{ .Values.controller.name }}
    app.kubernetes.io/version: {{ .Values.service.version }}
  name: {{ .Values.admission.name }}
  namespace: {{ .Values.service.namespace_definition.namespace }}
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - create
