apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: {{ .Values.service.components.controller }}
    app.kubernetes.io/instance: {{ .Values.controller.name }}
    app.kubernetes.io/name: {{ .Values.controller.name }}
    app.kubernetes.io/part-of: {{ .Values.controller.name }}
    app.kubernetes.io/version: {{ .Values.service.version }}
  name: {{ .Values.admission.name }}
  namespace: ingress-nginx
spec:
  ports:
  - appProtocol: https
    name: {{ .Values.controller.ports.https_port_name }}-{{ .Values.controller.ports.webhook_port_name }}
    port: {{ .Values.controller.ports.https_port }}
    targetPort: {{ .Values.controller.ports.webhook_port }}
  selector:
    app.kubernetes.io/component: {{ .Values.service.components.controller }}
    app.kubernetes.io/instance: {{ .Values.controller.name }}
    app.kubernetes.io/name: {{ .Values.controller.name }}
  type: ClusterIP
