apiVersion: v1
kind: Secret
metadata:
  labels:
    app: rabbitmq-tester-secret
  namespace: {{ .Release.Namespace }}
  name: rabbitmq-tester-secret
data:
  RABBIT_USERNAME: {{ .Values.config.rabbitmq_user | b64enc }}
  RABBIT_PASSWORD: {{ .Values.config.rabbitmq_password | b64enc }}
type: Opaque

