apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: role-access-test-secret
  namespace: a-ns
rules:
- apiGroups:
  - ""
  resourceNames:
  - test-secret
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
