apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  labels:
    app: {{ .Values.redis.name }}
  name: {{ .Values.redis.name }}
  namespace: {{ .Release.Namespace }}
spec:
  ingress:
  - ports:
    - port: {{ .Values.redis.service.port }}
      protocol: TCP
  - from:
    - namespaceSelector:
        matchLabels:
          app: {{ .Values.redis_networkpolicy.from.namespaceSelector.matchLabel.app }}
      podSelector:
        matchLabels:
          app-client: {{ .Values.redis_networkpolicy.from.podSelector_autogen.matchLabel.app_client }}
    - namespaceSelector:
        matchLabels:
          app: {{ .Values.redis_networkpolicy.from.namespaceSelector.matchLabel.app }}
      podSelector:
        matchLabels:
          app-client: {{ .Values.redis_networkpolicy.from.podSelector_redis_sentinel.matchLabel.app_client }}
    ports:
    - port: {{ .Values.redis.service.port }}
      protocol: TCP
  podSelector:
    matchLabels:
      app: {{ .Values.redis.name }}
  policyTypes:
  - Ingress

