apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.redis.config.name }}
  namespace: {{ .Release.Namespace }}
data:
  MASTERUSER_COMMENT: |
    #
    # master username
    # note:
    # 1. "NONE" (clear text) in the value for no master username setup
    #
  MASTERUSER: {{ .Values.redis_and_sentinel.config.masteruser }}
  MASTERAUTH_COMMENT: |
    #
    # master pass for masteruser
    # note:
    # 1. the password is the base64 encoded without newline
    # 2. "NONE" (clear text) in the value for no master pass setup
    #
  MASTERAUTH: {{ .Values.redis_and_sentinel.config.masterauth }}
  REQUIREPASS_COMMENT: |
    #
    # the redis client pass
    # note:
    # 1. the password is the base64 encoded without newline
    # 2. "NONE" (clear text) in the value for the redis client access without password
    #
  REQUIREPASS: {{ .Values.redis_and_sentinel.config.requirepass }}
  POD_PREFIX_NAME_COMMENT: |
    #
    # the prefix name of the redis statefulset pod
    #
  POD_PREFIX_NAME: {{ .Values.redis.name }}
  REDIS_SERVER_PORT_COMMENT: |
    #
    # The redis server listen port
    #
  REDIS_SERVER_PORT: "{{ .Values.redis.containerport }}"
  REDIS_SENTINAL_SERVER_NAME_COMMENT: |
    #
    # The sentinel server name
    #
  REDIS_SENTINAL_SERVER_NAME: "{{ .Values.redis_sentinel.name }}"
  REDIS_SENTINAL_SERVER_PORT_COMMENT: |
    #
    # The sentinel server listen port
    #
  REDIS_SENTINAL_SERVER_PORT: "{{ .Values.redis_sentinel.service.port }}"
  NUMBER_OF_DATABASE_COMMENT: |
    #
    # to set number of databases
    #
  NUMBER_OF_DATABASE: "{{ .Values.redis.config.number_of_database }}"

